# 📁 .github/workflows/build_database.yml

name: Crear Base de Datos desde CSV

on:
  workflow_dispatch: # Permite ejecutarlo manualmente

jobs:
  build-db:
    runs-on: ubuntu-latest

    steps:
      # 1. Clona el repositorio para tener acceso a los archivos
      - name: Checkout del código
        uses: actions/checkout@v4

      # 2. Configura el entorno de Python
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3. Instala las dependencias necesarias (en este caso, pandas)
      - name: Instalar dependencias
        run: |
          python -m pip install --upgrade pip
          pip install pandas

      # 4. Ejecuta el script para crear la base de datos
      #    Asumimos que el script se llama 'importar_a_db.py'
      - name: Ejecutar script de importación a DB
        run: python importar_a_db.py

      # 5. Sube el archivo de la base de datos resultante como un artefacto
      - name: Guardar base de datos como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: base-de-datos-sqlite
          path: analisis_sentimientos.db
