# 📁 .github/workflows/test_latest_model.yml (Versión Corregida)

name: Probar Último Modelo Entrenado

on:
  workflow_dispatch:

jobs:
  test-model:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      # ... (los pasos de configurar python e instalar dependencias no cambian)
      - name: Configurar Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: pip install -r requirements.txt
      
      # AÑADE LA LÍNEA 'token' AQUÍ ABAJO
      - name: Descargar último artefacto del modelo
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: train_model.yml
          name: modelo-afinad-artifact
          path: ./modelo_afinad/
          github_token: ${{ secrets.ACTIONS_TOKEN }}

      - name: Mostrar contenido descargado (para depuración)
        run: ls -R ./modelo_afinad

      - name: Ejecutar script de prueba
        run: python scripts/03_probar_modelo_afinado.py
